version: '3'

services:
  node:
    image: node:16.14
    container_name: cashforce-backend
    tty: true
    stdin_open: true
    command: sh -c "npm install && bash"
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    depends_on:
      - database
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_HOST: database
      PORT: 3001

  database:
    image: mysql:8.0.29
    container_name: cashforce_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cashforce_v3
    ports:
      - 33061:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro