version: '3'

services:
  frontend:
    container_name: cashforce-frontend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app-frontend/src
    working_dir: /app-frontend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]  
      timeout: 10s
      retries: 5

  node:
    build: ./backend
    container_name: cashforce-backend
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app-backend
    depends_on:
      - database
    ports:
      - 3001:3001
    volumes:
      - ./backend/src:/app-backend/src
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_HOST: database
      PORT: 3001
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5

  database:
    image: mysql:8.0.29
    container_name: cashforce_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cashforce_v3
    ports:
      - 33061:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro